- block:
  - name: give deployer user access to ssh agent
    shell: |
      if [ -n "$SSH_AUTH_SOCK" ]; then
        setfacl -m u:{{ deploy_user }}:rw $SSH_AUTH_SOCK ;
        setfacl -m u:{{ deploy_user }}:x $(dirname $SSH_AUTH_SOCK)
      fi
    become_user: root

  - name: deploy platform code from github
    git: repo={{ platform_api_repo_url }} dest={{ platform_api_base_path }} version={{ platform_api_version | default("master") }} force={{ platform_api_update }} update={{ platform_api_update }}
    register: st_git_pull
    notify: run platform api migrations

  - name: install dependencies using composer
    composer: command=install working_dir={{ platform_api_base_path }}

  - name: create .env file in the server (method 1 - from project's .env.deploy file)
    include_role: 
      name: ansible-dotenv-generator
    vars:
      dest: "{{ platform_api_base_path }}/.env"
      dotenv_sample: "{{ platform_api_base_path }}/{{ platform_api_dotenv_sample }}"
      env: "{{ platform_api_env }}"
      dest_owner: "{{ deploy_user }}"
    args:
      allow_duplicates: True
    when: platform_api_env is defined

  - name: copy .env file to server (method 2 - playbook template file)
    template: src="templates/platform-dot-env.j2" dest={{ platform_api_base_path }}/.env mode=0644
    when: platform_api_env is not defined

  - name: copy cdn config to server
    template: src="templates/platform-config-cdn.j2" dest={{ platform_api_base_path }}/application/config/cdn.php mode=0644
    when: platform_cdn

  - name: copy media config to server
    template: src="templates/platform-config-media.j2" dest={{ platform_api_base_path }}/application/config/media.php mode=0644

  - name: copy ratelimiter config to server
    template: src="templates/platform-config-ratelimiter.j2" dest={{ platform_api_base_path }}/application/config/ratelimiter.php mode=0644

  - name: change permissions on cache, log and uploads to 0777
    file: path={{ platform_api_base_path }}/application/{{item}} mode=0777 recurse=yes
    with_items:
      - cache
      - logs
      - media/uploads

  become: yes
  become_user: "{{ deploy_user }}"

- block:
  - name: Set mailto on crontab
    cronvar:
      name: "MAILTO"
      value: "{{ platform_api_cron_email }}"
      user: "{{ deploy_user }}"

  - name: Add cron jobs for platform api
    cron:
      name: "Ushahidi Platform {{ item.command }}"
      user: "{{ deploy_user }}"
      job: "cd {{ platform_api_base_path }} && {{ platform_api_base_path }}/bin/ushahidi {{ item.command }} >> /dev/null"
      minute: "{{ item.minutes }}"
    with_items: "{{ platform_api_ushahidi_cli_cronjobs | union(platform_api_additional_ushahidi_cli_cronjobs) }}"

  when: not platform_api_multisite_setup and platform_api_cronjobs
  become: yes
  become_user: root